version: "3"

services:
  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    links:
      - backend-service
    networks:
      - webappnetwork

  backend-service:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data_node:/data/db
    ports:
      - "27017:27017"
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    links:
      - frontend-service
      - backend-service
      - mongodb
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
